apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: voltha
spec:
  type: NodePort
  selector:
    app: ingress-nginx
  ports:
  - name: http
    port: 80
    nodePort: 30080
    targetPort: http
  - name: https
    port: 443
    nodePort: 30443
    targetPort: https
