# RG 
- name: "VOLT-HA Teardown | Stop RG"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/rg.yml
  run_once: true

# ONU
- name: "VOLT-HA Teardown | Stop ONU"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/onu.yml
  run_once: true

# OLT
- name: "VOLT-HA Teardown | Stop OLT"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/olt.yml
  run_once: true

# CNI Genie 
- name: "VOLT-HA Teardown | Stop CNI Genie"
  command: kubectl delete --ignore-not-found=true -f https://raw.githubusercontent.com/Huawei-PaaS/CNI-Genie/master/conf/1.8/genie.yaml
  run_once: true

# ONOS
- name: "VOLT-HA Teardown | Stop ONOS"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/onos.yml
  run_once: true

# FreeRADIUS
- name: "VOLT-HA Teardown | Stop FreeRADIUS"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/freeradius.yml
  run_once: true

# FreeRADIUS Config
- name: "VOLT-HA Teardown | Remove FreeRADIUS Configuration"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/freeradius-config.yml
  run_once: true

# Dashd and Shovel
- name: "VOLT-HA Teardown | Stop DASHD and SHOVEL"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/stats.yml
  run_once: true

# Grafana
- name: "VOLT-HA Teardown | Stop Grafana"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/grafana.yml
  run_once: true

# NETCONF
- name: "VOLT-HA Teardown | Stop NETCONF"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/netconf.yml
  run_once: true

# Voltha CLI
- name: "VOLT-HA Teardown | Stop VOLT-HA CLI"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/vcli.yml
  run_once: true

# Envoy (for etcd)
- name: "VOLT-HA Teardown | Stop Envoy (for etcd)"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/envoy_for_etcd.yml
  run_once: true

# OFagent
- name: "VOLT-HA Teardown | Stop OpenFlow Agent"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/ofagent.yml
  run_once: true

# Voltha Core (for etcd)
- name: "VOLT-HA Teardown | Stop VOLT-HA core (for etcd)"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/vcore_for_etcd.yml
  run_once: true

# Etcd cluster
- name: "VOLT-HA Teardown | Stop etcd cluster"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/operator/etcd/etcd_cluster.yml
  run_once: true

# Etcd operator
- name: "VOLT-HA Teardown | Stop etcd operator"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/operator/etcd/operator.yml
  run_once: true

# Etcd cluster role binding
- name: "VOLT-HA Teardown | Stop etcd cluster role binding"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/operator/etcd/cluster_role_binding.yml
  run_once: true

# Etcd cluster role
- name: "VOLT-HA Teardown | Stop etcd cluster role"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/operator/etcd/cluster_role.yml
  run_once: true

# Fluentd
- name: "VOLT-HA Teardown | Stop fluentd"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/fluentd.yml
  run_once: true

# Fluentd Config
- name: "VOLT-HA Teardown | Remove Fluentd Configuration"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/fluentd-config.yml
  run_once: true

# Kafka
- name: "VOLT-HA Teardown | Stop kafka"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/kafka.yml
  run_once: true

# Zookeeper
- name: "VOLT-HA Teardown | Stop zookeeper"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/zookeeper.yml
  run_once: true

# Ingress
- name: "VOLT-HA Teardown | Stop Ingress Controller"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/ingress
  run_once: true

# Namespace
- name: "VOLT-HA Teardown | Remove Namespace"
  command: kubectl delete --ignore-not-found=true -f /vagrant/k8s/namespace.yml
  run_once: true
