apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
  namespace: voltha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
      annotations:
        cni: "calico"      
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.9.1
        command:
        - etcd-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

